- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install packages
      command: pkg_add -D snapshot {{ item }}
      loop:
        - vim--no_x11
        - curl
        - ImageMagick
        - firefox
        - chromium
        - feh
        - ghostwriter
        - hack-fonts
        - git
        - doas
        - go
        - rust
        - github-cli
        - terraform
        - ruby-3.4.1p1
        - ruby-shims
    - name: Install bundler
      command: gem install bundler
