setxkbmap -option caps:escape

export ENV=$HOME/.kshrc

feh --bg-center /usr/local/share/wallpapers/current.jpg &

xclock -render -digital -twentyfour -geometry +40+1227 -update 60 \
  -fg "#3A3A3C" -bg "#FFFFFF" \
  -strftime "%H:%M" \
  -face "Helvetica:size=42:weight=bold" &

xclock -render -digital -geometry 255x35+40+1200 -update 3600 \
  -fg "#3A3A3C" -bg "#FFFFFF" \
  -strftime "%A, %B %d" \
  -face "Helvetica:size=14" &


exec /usr/X11R6/bin/cwm
